# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'EyeTracker' do
source 'https://github.com/CocoaPods/Specs.git'
pod 'Alamofire', '~> 3.0'
pod "AWSiOSSDKv2"

end

